version: '3'

services:
  front:
    image:  gpolicante/curso-docker
    networks:
      - front
      - traefik_traefik
    deploy: 
     labels: 
     - "traefik.port=80"
     - "traefik.backend=front"
     - "traefik.backend.healthcheck.port=80"
     - "traefik.frontend.rule=Host:front.devops.com"
     - "traefik.backend.healthcheck.interval=2s"
     - "traefik.backend.loadbalancer.sticky=true"
     -  "traefik.docker.network=traefik_traefik"
     replicas: 1 
     restart_policy: 
      condition: on-failure
     placement: 
      constraints:
        - node.role == worker
     resources: 
       limits: 
         cpus: '0.5'
         memory: '350M'
       reservations: 
         cpus: '0.1'
         memory: '256M'   


networks: 
 front: 
 traefik_traefik: 
  external: 
   name: traefik_traefik
